resources:
- name: todos-ui-docker-image
  type: docker-image
  source:
    username: ((CONTAINER_REGISTRY_USER))
    password: ((CONTAINER_REGISTRY_PASS))
    repository: dektlong/dekt-todo-ui

- name: source-code
  type: git
  source:
    uri: https://github.com/dektlong/todo-ui.git
    branch: master
    paths:
    - todo-ui/**/*
    - todo-ui/**

- name: push-TAS-UAT-cloud
  type: cf
  source:
    api: ((TAS_UAT_API))
    username: ((TAS_UAT_USER))
    password: ((TAS_UAT_PASS))
    organization: ((TAS_UAT_ORG))
    space: ((TAS_UAT_SPACE))
    skip_cert_check: false

jobs:
- name: publish
  public: true
  serial: true
  plan:
  - get: source-code
    trigger: true
  - put: todos-ui-docker-image
    params:
      build: source-code/todo-ui

- name: push-to-pcf
  public: true
  serial: true
  plan:
  - get: source-code
  - get: todos-ui-docker-image
    passed:
    - publish
    trigger: true
  - put: push-TAS-UAT-cloud
    params:
      manifest: source-code/todo-ui/manifest-uat.yml
