resources:
- name: todos-ui-docker-image
  type: docker-image
  source:
    username: ((CONTAINER_REGISTRY_USER))
    password: ((CONTAINER_REGISTRY_PASS))
    repository: dektlong/dekt-todo-ui

- name: source-code
  type: git
  source:
    uri: https://github.com/dektlong/todo-ui.git
    branch: master
 
- name: TAS-TEST-cloud
  type: cf
  source:
    api: {{TAS_TEST_API}}
    username: {{TAS_TEST_USER}}
    password: {{TAS_TEST_PASS}}
    organization: {{TAS_TEST_ORG}}
    space: {{TAS_TEST_SPACE}}
    skip_cert_check: true
    
- name: TAS-UAT-cloud
  type: cf
  source:
    api: {{TAS_UAT_API}}
    username: {{TAS_UAT_USER}}
    password: {{TAS_UAT_PASS}}
    organization: {{TAS_UAT_ORG}}
    space: {{TAS_UAT_SPACE}}
    skip_cert_check: true
    
- name: TAS-PROD-cloud
  type: cf
  source:
    api: {{TAS_PROD_API}}
    username: {{TAS_PROD_USER}}
    password: {{TAS_PROD_PASS}}
    organization: {{TAS_PROD_ORG}}
    space: {{TAS_PROD_SPACE}}
    skip_cert_check: true


jobs:
- name: publish
  public: true
  serial: true
  plan:
  - get: source-code
    trigger: true
  - put: todos-ui-docker-image
    params:
      build: source-code

- name: push-to-pcf
  public: true
  serial: true
  plan:
  - get: source-code
  - get: todos-ui-docker-image
    passed:
    - publish
    trigger: true
  - put: TAS-UAT-cloud
    params:
      manifest: source-code/manifest-uat.yml
