resources:
- name: todo-ui-docker-image
  type: docker-image
  source:
    username: ((CONTAINER_REGISTRY_USER))
    password: ((CONTAINER_REGISTRY_PASS))
    repository: dektlong/dekt-todo-ui

- name: todo-ui-git-repo
  type: git
  check_every: 5s
  source:
    uri: https://github.com/dektlong/todo-ui.git
    branch: master
    
- name: TAS-TEST-cloud
  type: cf
  source:
    api: {{TAS_TEST_API}}
    username: {{TAS_TEST_USER}}
    password: {{TAS_TEST_PASS}}
    organization: {{TAS_TEST_ORG}}
    space: {{TAS_TEST_SPACE}}
    skip_cert_check: true
    
- name: TAS-UAT-cloud
  type: cf
  source:
    api: {{TAS_UAT_API}}
    username: {{TAS_UAT_USER}}
    password: {{TAS_UAT_PASS}}
    organization: {{TAS_UAT_ORG}}
    space: {{TAS_UAT_SPACE}}
    skip_cert_check: true
    
- name: TAS-PROD-cloud
  type: cf
  source:
    api: {{TAS_PROD_API}}
    username: {{TAS_PROD_USER}}
    password: {{TAS_PROD_PASS}}
    organization: {{TAS_PROD_ORG}}
    space: {{TAS_PROD_SPACE}}
    skip_cert_check: true
    

jobs:
- name: publish-todo-ui
  plan:
  - get: todo-ui-git-repo
    trigger: true
  - put: todo-ui-docker-image
    params:
      build: todo-ui-git-repo

- name: test-todo-ui
  plan:
  - get: todo-ui-git-repo
  - get: todo-ui-docker-image
    passed:
    - publish-todo-ui
    trigger: true
  - put: TAS-TEST-cloud
    params:
      manifest: source-code/todo-ui/manifest-test.yml
      
- name: integrate-todo-ui
  plan:
  - get: todo-ui-git-repo
  - get: todo-ui-docker-image
    passed:
    - test-todo-ui
    trigger: true
  - put: TAS-UAT-cloud
    params:
      manifest: source-code/todo-ui/manifest-uat.yml

- name: ship-todo-ui
  serial: true
  plan:
  - get: todo-ui-git-repo
  - get: todo-ui-docker-image
    passed:
    - integrate-todo-ui
    trigger: true
  - put: TAS-PROD-cloud
    params:
      manifest: source-code/todo-ui/manifest-prod.yml
      
